---
- name: Install Java 1.7 and some basic dependencies
  ansible.builtin.yum:
    name:
      - unzip
      - java-1.7.0-openjdk
      - libselinux-python
      - libsemanage-python
    state: present

- name: Download JBoss from jboss.org
  ansible.builtin.get_url:
    url: http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip
    dest: /opt/jboss-as-7.1.1.Final.zip

- name: Extract archive
  ansible.builtin.unarchive:
    dest: /usr/share
    src: /opt/jboss-as-7.1.1.Final.zip
    creates: /usr/share/jboss-as
    copy: false

# Rename the dir to avoid encoding the version in the init script

- name: Rename install directory
  args:
    chdir: /usr/share
    creates: /usr/share/jboss-as
  ansible.builtin.command: /bin/mv jboss-as-7.1.1.Final jboss-as

- name: Copying standalone.xml configuration file
  notify: restart jboss
  ansible.builtin.template:
    src: standalone.xml
    dest: /usr/share/jboss-as/standalone/configuration/

- name: Add group "jboss"
  ansible.builtin.group:
    name: jboss

- name: Add user "jboss"
  ansible.builtin.user:
    name: jboss
    group: jboss
    home: /usr/share/jboss-as

- name: Change ownership of JBoss installation
  ansible.builtin.file:
    path: /usr/share/jboss-as/
    owner: jboss
    group: jboss
    state: directory
    recurse: true

- name: Copy the init script
  ansible.builtin.copy:
    src: jboss-as-standalone.sh
    dest: /etc/init.d/jboss
    mode: 493

- name: Workaround for systemd bug
  ignore_errors: true
  ansible.builtin.shell: service jboss start && chkconfig jboss on

- name: Enable JBoss to be started at boot
  ansible.builtin.service:
    name: jboss
    enabled: true
    state: started

- name: deploy iptables rules
  when: ansible_distribution_major_version != "7"
  notify: restart iptables
  ansible.builtin.template:
    src: iptables-save
    dest: /etc/sysconfig/iptables

- name: Ensure that firewalld is installed
  when: ansible_distribution_major_version == "7"
  ansible.builtin.yum:
    name: firewalld
    state: present

- name: Ensure that firewalld is started
  when: ansible_distribution_major_version == "7"
  ansible.builtin.service:
    name: firewalld
    state: started

- name: deploy firewalld rules
  when: ansible_distribution_major_version == "7"
  ansible.posix.firewalld:
    immediate: true
    port: "{{ item }}"
    state: enabled
    permanent: true
  loop:
    - "{{ http_port }}/tcp"
    - "{{ https_port }}/tcp"
